# Generated by Django 2.1.7 on 2019-02-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0002_auto_20190129_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit_name', models.CharField(max_length=30)),
                ('fruit_price', models.IntegerField()),
            ],
        ),
    ]
