# Generated by Django 2.1.7 on 2019-02-20 05:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0003_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='fruit_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
